### ISSUE TITLE
Issue dumping TC58NVG2S0HTA00 dumps only first page with oob for every page requested

### ISSUE THREAD

**Issue by 46cv8** [conchyliculture/Yand#14]
Hey I'm thinking there may be some timing issue specific to my Kioxia chip TC58NVG2S0HTA00

The command I run is "yand_cli.py  -P 4096,256 -B 64 -K 2048 -r -f ../dump.bin"

The result is that it only dumps the first page with oob repeating 64x2048 (131072) times.
I haven't tried monitoring with a logic analyzer just yet but I'm curious if you have any ideas where the issue might lay.

I confirmed from the datasheet https://media.digikey.com/pdf/Data%20Sheets/Toshiba%20PDFs/KIOXIA_TC58NVG2S0HTA00_Rev2.00_E191001C.pdf that address cycles is indeed 5. 
"Then the Read operation after the power on sequence is executed by the setting of only five address cycles and “30h” command."

I also attempted using 6mhz clock instead of the 30mhz clock by using the following.
```
self.ftdi.write_data(bytearray([ftdi.Ftdi.ENABLE_CLK_DIV5]))
```
But it didn't work and resulted in the following error
```
Traceback (most recent call last):
  File "/tmp/tmp.qbakTEsMHH/bin/yand_cli.py", line 4, in <module>
    __import__('pkg_resources').run_script('yand==20190926', 'yand_cli.py')
  File "/tmp/tmp.qbakTEsMHH/lib/python3.8/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/tmp/tmp.qbakTEsMHH/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "/tmp/tmp.qbakTEsMHH/lib/python3.8/site-packages/yand-20190926-py3.8.egg/EGG-INFO/scripts/yand_cli.py", line 207, in <module>
  File "/tmp/tmp.qbakTEsMHH/lib/python3.8/site-packages/yand-20190926-py3.8.egg/EGG-INFO/scripts/yand_cli.py", line 160, in Main
  File "/tmp/tmp.qbakTEsMHH/lib/python3.8/site-packages/yand-20190926-py3.8.egg/yand/nand_interface.py", line 178, in DumpFlashToFile
  File "/tmp/tmp.qbakTEsMHH/lib/python3.8/site-packages/yand-20190926-py3.8.egg/yand/nand_interface.py", line 202, in ReadPage
  File "/tmp/tmp.qbakTEsMHH/lib/python3.8/site-packages/yand-20190926-py3.8.egg/yand/ftdi_device.py", line 93, in Read
  File "/tmp/tmp.qbakTEsMHH/lib/python3.8/site-packages/pyftdi-0.54.0-py3.8.egg/pyftdi/ftdi.py", line 1782, in write_data
    length = self._write(data[offset:offset+write_size])
  File "/tmp/tmp.qbakTEsMHH/lib/python3.8/site-packages/pyftdi-0.54.0-py3.8.egg/pyftdi/ftdi.py", line 2092, in _write
    raise FtdiError('UsbError: %s' % str(ex)) from None
pyftdi.ftdi.FtdiError: UsbError: [Errno 110] Operation timed out
  0%|                           
```

I was so surprized that it actually appeared to be dumping the first page of the nand that I figured it must have all just worked, as I was totally expecting some incompatibility issue or something. It seems that perhaps there is just some timing issue or something though.

**Comment by 46cv8** [comment]
Just to update here I managed to hookup a logic analyzer and confirmed that the addresses are being sent properly and they do comply with the requirements from the datasheet timing diagram. The only thing I noticed that was really off was that the ready signal was jumping all over the place. 

![address_latch_timing_diagram](https://user-images.githubusercontent.com/58377031/219867340-85a72d7a-085d-49dd-9727-9dda4756bf8c.png)
![logic_analyzer_capture](https://user-images.githubusercontent.com/58377031/219867346-07a103b1-6f0a-4d3f-b7b5-b30b11dedf31.png)

I found another git project with someone else who said they couldn't get dumpflash to work (which is what this project is based on) so I'm going to try their project. https://github.com/vmallet/ftdi-nand-flash-tool
On their wiring page they say that the ready signal needs a 10k pull-up to 3v3. I wonder if that might be part of the issue using this code?

EDIT:
Putting a pull-up on ready didn't help with it always returning data for address 0. Or the oscillating of the ready signal at 60 mhz

**Comment by 46cv8** [comment]
Ok so I'm just silly :) I realized my mistake. The first 2000 pages all contain the same data, after that there is more varied data. I'm guessing whatever controller they are using is designed to have a large amount of redundancy for the first block or something. Both your tool and the bitbang tool at https://github.com/vmallet/ftdi-nand-flash-tool are returning the same results as far as I can tell. I'm going to close this issue for now as I'm pretty sure it's just my mistake
